"use client";
import { useRouter } from "next/navigation";

export default function PrivacyPage() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-slate-950 text-white flex flex-col">
      <header className="px-8 py-5 border-b border-slate-800">
        <div className="max-w-3xl mx-auto">
          <button
            onClick={() => router.push("/")}
            className="text-xl font-semibold tracking-tight hover:opacity-80 transition-opacity"
          >
            Smart<span className="text-blue-400">Log</span>
          </button>
        </div>
      </header>

      <main className="flex-1 max-w-3xl mx-auto px-6 py-12 w-full">
        <h1 className="text-3xl font-semibold mb-2">Privacy Policy</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: May 8, 2026</p>

        <div className="prose prose-invert prose-slate max-w-none space-y-8 text-slate-300 leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Who we are</h2>
            <p>SmartLog is a trading journal and experiment-tracking tool operated by Marcos Bulcão. Our website is <strong className="text-white">app.smartlogtrading.com</strong>. You can reach us at <a href="mailto:marcos@smartlogtrading.com" className="text-blue-400 hover:text-blue-300">marcos@smartlogtrading.com</a>.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. What data we collect</h2>
            <p>We collect only what is necessary to provide the service:</p>
            <ul className="list-disc list-inside space-y-1 mt-2 text-slate-400">
              <li><strong className="text-slate-300">Account data:</strong> email address, name (if provided), authentication method (email/password or Google).</li>
              <li><strong className="text-slate-300">Usage data:</strong> trading experiments you create, variants, trade log entries (hit/miss), and conversation history generated by the AI setup flow.</li>
              <li><strong className="text-slate-300">Payment data:</strong> billing is handled entirely by Stripe. We store only a reference to your Stripe customer ID — we never see or store your card details.</li>
              <li><strong className="text-slate-300">Technical data:</strong> standard server logs (IP address, browser type, pages visited) for security and debugging.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. How we use your data</h2>
            <ul className="list-disc list-inside space-y-1 text-slate-400">
              <li>To provide and improve the SmartLog service.</li>
              <li>To manage your account and subscription.</li>
              <li>To respond to support requests.</li>
              <li>To send transactional emails (receipts, password resets). We do not send marketing emails without your consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Data storage and security</h2>
            <p>Your data is stored on <strong className="text-white">Supabase</strong> (PostgreSQL database hosted on AWS). We use industry-standard encryption in transit (HTTPS) and at rest. Access to production data is restricted to authorised personnel only.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Third-party services</h2>
            <ul className="list-disc list-inside space-y-1 text-slate-400">
              <li><strong className="text-slate-300">Supabase</strong> — authentication and database.</li>
              <li><strong className="text-slate-300">Stripe</strong> — payment processing.</li>
              <li><strong className="text-slate-300">Anthropic (Claude API)</strong> — AI-powered conversation during experiment setup.</li>
              <li><strong className="text-slate-300">Resend</strong> — transactional email delivery.</li>
              <li><strong className="text-slate-300">Vercel</strong> — application hosting.</li>
            </ul>
            <p className="mt-2">Each of these services has its own privacy policy. We do not sell your data to any third party.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Your rights</h2>
            <p>You may at any time:</p>
            <ul className="list-disc list-inside space-y-1 mt-2 text-slate-400">
              <li>Request a copy of your personal data.</li>
              <li>Request deletion of your account and all associated data.</li>
              <li>Correct inaccurate information.</li>
            </ul>
            <p className="mt-2">To exercise these rights, contact us at <a href="mailto:marcos@smartlogtrading.com" className="text-blue-400 hover:text-blue-300">marcos@smartlogtrading.com</a>.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Cookies</h2>
            <p>SmartLog uses only essential cookies required for authentication (session tokens). We do not use tracking or advertising cookies.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Changes to this policy</h2>
            <p>We may update this policy occasionally. We will notify you of significant changes via email or a notice in the app. Continued use of SmartLog after changes constitutes acceptance of the updated policy.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Contact</h2>
            <p>Questions about this policy? Email us at <a href="mailto:marcos@smartlogtrading.com" className="text-blue-400 hover:text-blue-300">marcos@smartlogtrading.com</a>.</p>
          </section>

        </div>
      </main>

      <footer className="border-t border-slate-800 px-8 py-6">
        <div className="max-w-3xl mx-auto flex gap-6 text-xs text-slate-600">
          <button onClick={() => router.push("/terms")} className="hover:text-slate-400 transition-colors">Terms of Service</button>
          <button onClick={() => router.push("/contact")} className="hover:text-slate-400 transition-colors">Contact</button>
        </div>
      </footer>
    </div>
  );
}
