// THE MAP — full navigation structure for Trading Without Ego
// 126 destinations across 9 content layers.
// Used by: landing page tree, book reader prev/next, AI companion context

export const BOOK_MAP = [
  {
    id: "entry",
    title: "ENTRY",
    subtitle: "The Pain That Brought You Here",
    slug: "entry",
    tone: "Emotional-first. Recognition before education.",
    free: true,
    children: [
      {
        id: "entry-1",
        title: "ENTRY.1",
        subtitle: "The Impulse and the Fallacy",
        slug: "entry/1",
        free: true,
        starred: false,
        oneliner: "The specific shape of the pain — three properties that make it different from ordinary bad days",
      },
      {
        id: "entry-2",
        title: "ENTRY.2",
        subtitle: "The Old Paradigm",
        slug: "entry/2",
        free: true,
        starred: false,
        oneliner: "Where the standard model (emotions = enemy, discipline = solution) breaks down",
      },
      {
        id: "entry-3",
        title: "ENTRY.3",
        subtitle: "The Self-Blame Loop",
        slug: "entry/3",
        free: true,
        starred: true,
        oneliner: "The full anatomy of the loop — and why self-blame protects the very model that generates it",
      },
      {
        id: "entry-4",
        title: "ENTRY.4",
        subtitle: "The Verdict",
        slug: "entry/4",
        free: true,
        starred: false,
        oneliner: "The character conclusion the loop produces — and why it accelerates the next iteration",
      },
      {
        id: "entry-5",
        title: "ENTRY.5",
        subtitle: "The Two Questions",
        slug: "entry/5",
        free: true,
        starred: false,
        oneliner: "The two questions every stuck trader is asking — and the two-step path to their answers",
      },
    ],
  },
  {
    id: "act1",
    title: "ACT I",
    subtitle: "The Reframe",
    slug: "act/1",
    tone: "The old model dismantled; the new one introduced.",
    free: true,
    children: [
      {
        id: "act1-1",
        title: "I.1",
        subtitle: "Emotion is Not the Enemy",
        slug: "act/1/1",
        free: true,
        starred: false,
        oneliner: "Emotions are goal-directed signals, not interference — the single most important reframe",
      },
      {
        id: "act1-2",
        title: "I.2",
        subtitle: "Why the Loop is Inevitable",
        slug: "act/1/2",
        free: true,
        starred: true,
        oneliner: "The HUG: the goal the impulse is protecting, and why suppression guarantees repetition",
      },
      {
        id: "act1-3",
        title: "I.3",
        subtitle: "Why Willpower Always Fails",
        slug: "act/1/3",
        free: false,
        starred: false,
        oneliner: "The structural reason willpower produces temporary success and reliable long-term failure",
      },
      {
        id: "act1-4",
        title: "I.4",
        subtitle: "The New Paradigm",
        slug: "act/1/4",
        free: false,
        starred: false,
        oneliner: "Failure as misdiagnosis, not character verdict — the foundation everything else builds on",
      },
    ],
  },
  {
    id: "act2",
    title: "ACT II",
    subtitle: "The Operating System",
    slug: "act/2",
    tone: "The internal architecture of trading decisions.",
    free: false,
    children: [
      {
        id: "act2-1",
        title: "II.1",
        subtitle: "Emotions as Goal Protectors",
        slug: "act/2/1",
        free: false,
        starred: false,
        oneliner: "Each emotion is a signal: a goal is threatened — the four reward types and four goal layers",
      },
      {
        id: "act2-2",
        title: "II.2",
        subtitle: "All Habits Are Successful",
        slug: "act/2/2",
        free: false,
        starred: false,
        oneliner: "Every impulsive behaviour is successfully protecting something — what each pattern is hired to do",
      },
      {
        id: "act2-3",
        title: "II.3",
        subtitle: "The Mental Congress",
        slug: "act/2/3",
        free: false,
        starred: true,
        oneliner: "The Strategist, Protector, Speculator, and Critic — how the internal parliament governs decisions",
      },
      {
        id: "act2-4",
        title: "II.4",
        subtitle: "The 3 Tasks",
        slug: "act/2/4",
        free: false,
        starred: false,
        oneliner: "WHAT (clear goals), HOW (tested methods), WHAT TO EXPECT (realistic expectations)",
      },
      {
        id: "act2-5",
        title: "II.5",
        subtitle: "The Pirates' Dilemma",
        slug: "act/2/5",
        free: false,
        starred: true,
        oneliner: "The three pirates, the pirate fee, and the ESS as the most sustainable mixed strategy",
      },
      {
        id: "act2-6",
        title: "II.6",
        subtitle: "Keys to Sustainable Discipline",
        slug: "act/2/6",
        free: false,
        starred: false,
        oneliner: "Three structural shifts: pre-negotiate the fee, convert uncertainty to variant, build the evidence base",
      },
    ],
  },
  {
    id: "act3",
    title: "ACT III",
    subtitle: "The Method",
    slug: "act/3",
    tone: "Practical, sequential, specific.",
    free: false,
    children: [
      {
        id: "act3-1",
        title: "III.1",
        subtitle: "The Two Stages of Structured Decisions",
        slug: "act/3/1",
        free: false,
        starred: false,
        oneliner: "From vague doubt to true conviction — the full arc",
      },
      {
        id: "act3-2",
        title: "III.2",
        subtitle: "Stage 1 — Remove Regret",
        slug: "act/3/2",
        free: false,
        starred: true,
        oneliner: "Four steps: name the uncertainty, name the alternatives, test rather than repress, judge by process",
      },
      {
        id: "act3-3",
        title: "III.3",
        subtitle: "Stage 2 — Remove Uncertainty",
        slug: "act/3/3",
        free: false,
        starred: false,
        oneliner: "Event-thinking vs. sample-thinking; how the conviction loop closes",
      },
      {
        id: "act3-4",
        title: "III.4",
        subtitle: "Three Types of Competing Alternatives",
        slug: "act/3/4",
        free: false,
        starred: false,
        oneliner: "Zero-Sum, Hierarchic Goals, Pirates' Dilemma — and the cost of misdiagnosis",
      },
      {
        id: "act3-5",
        title: "III.5",
        subtitle: "How to Build a Repeatable Setup",
        slug: "act/3/5",
        free: false,
        starred: false,
        oneliner: "The four elements: Situation, Conditions with variants, Structural Stop, Targets",
      },
      {
        id: "act3-6",
        title: "III.6",
        subtitle: "Conditions, Variants, and Why Both Matter",
        slug: "act/3/6",
        free: false,
        starred: false,
        oneliner: "The variant-testing principle — with example tables and the setup card format",
      },
      {
        id: "act3-7",
        title: "III.7",
        subtitle: "Logging That Actually Works",
        slug: "act/3/7",
        free: false,
        starred: false,
        oneliner: "What to log, how long it takes, the five minimum fields",
      },
      {
        id: "act3-8",
        title: "III.8",
        subtitle: "Reports: From Data to Confidence",
        slug: "act/3/8",
        free: false,
        starred: false,
        oneliner: "Seven report types; sample size markers; the conviction loop",
      },
    ],
  },
  {
    id: "act4",
    title: "ACT IV",
    subtitle: "The Arrival",
    slug: "act/4",
    tone: "Identity shift — not new lessons, but recognition.",
    free: false,
    children: [
      {
        id: "act4-1",
        title: "IV.1",
        subtitle: "From Fighter to Governor",
        slug: "act/4/1",
        free: false,
        starred: false,
        oneliner: "The identity shift in full — Fighter's loop vs. Strategist's loop; the one diagnostic question",
      },
      {
        id: "act4-2",
        title: "IV.2",
        subtitle: "The ESS",
        slug: "act/4/2",
        free: false,
        starred: false,
        oneliner: "Three properties of a stable strategy; practical ESS designs for FOMO, Early Exit, Revenge Trading",
      },
      {
        id: "act4-3",
        title: "IV.3",
        subtitle: "Discipline Redefined",
        slug: "act/4/3",
        free: false,
        starred: false,
        oneliner: "New definition: output of a low-friction system; three structural shifts with case studies",
      },
      {
        id: "act4-4",
        title: "IV.4",
        subtitle: "Making vs. Sustaining a Decision",
        slug: "act/4/4",
        free: false,
        starred: false,
        oneliner: "Willpower as emergency response; conviction without certainty as the Strategist's end state",
      },
    ],
  },
  {
    id: "patterns",
    title: "PATTERN LIBRARY",
    subtitle: "All 15 Patterns",
    slug: "patterns",
    tone: "Self-contained destinations. Arrive via link; find everything you need.",
    free: false,
    children: [
      { id: "p1",  title: "P1",  subtitle: "FOMO / Early Entry",         slug: "patterns/fomo",             free: false, starred: false, oneliner: "FOMO isn't about missing the move — it's about not trusting a process you haven't verified yet" },
      { id: "p2",  title: "P2",  subtitle: "Hesitation",                  slug: "patterns/hesitation",       free: false, starred: false, oneliner: "Hesitation isn't fear of being wrong — it's the mind refusing to act on an incomplete question" },
      { id: "p3",  title: "P3",  subtitle: "Early Exit",                  slug: "patterns/early-exit",       free: false, starred: false, oneliner: "Early exits aren't about protecting profits — they're about relief" },
      { id: "p4",  title: "P4",  subtitle: "Revenge Trading",             slug: "patterns/revenge",          free: false, starred: false, oneliner: "Revenge trading isn't irrational — it's the most rational response to an injustice" },
      { id: "p5",  title: "P5",  subtitle: "Stop Loss Tampering",         slug: "patterns/stop-tampering",   free: false, starred: false, oneliner: "Moving your stop isn't risk management — it's renegotiating a decision made in cold blood" },
      { id: "p6",  title: "P6",  subtitle: "Overtrading",                 slug: "patterns/overtrading",      free: false, starred: false, oneliner: "Overtrading isn't taking too many trades — it's satisfying a need unrelated to the setup" },
      { id: "p7",  title: "P7",  subtitle: "Greed / Holding Too Long",    slug: "patterns/greed",            free: false, starred: false, oneliner: "Greed isn't wanting too much — it's the Speculator renegotiating mid-trade at maximum leverage" },
      { id: "p8",  title: "P8",  subtitle: "Redemption Trap",             slug: "patterns/redemption",       free: false, starred: false, oneliner: "The redemption trade doesn't recover the loss — it recovers the story" },
      { id: "p9",  title: "P9",  subtitle: "Overconfidence Bias",         slug: "patterns/overconfidence",   free: false, starred: false, oneliner: "Confidence from recent wins is not statistical confidence — it's recency" },
      { id: "p10", title: "P10", subtitle: "Loss Aversion",               slug: "patterns/loss-aversion",    free: false, starred: false, oneliner: "Loss aversion isn't a flaw — it's an evolved threat response running in the wrong environment" },
      { id: "p11", title: "P11", subtitle: "Confirmation Bias",           slug: "patterns/confirmation",     free: false, starred: false, oneliner: "You're not analysing the chart — you're looking for permission to do what you've already decided" },
      { id: "p12", title: "P12", subtitle: "Hindsight Bias",              slug: "patterns/hindsight",        free: false, starred: false, oneliner: "Looking at a past chart is always cheating — you're solving a puzzle with the answer visible" },
      { id: "p13", title: "P13", subtitle: "Anchoring / Recency Bias",    slug: "patterns/anchoring",        free: false, starred: false, oneliner: "Your last few trades aren't information about your edge — they're information about variance" },
      { id: "p14", title: "P14", subtitle: "Herd Mentality",              slug: "patterns/herd",             free: false, starred: false, oneliner: "Following the crowd isn't a failure of independence — it's the social goal overriding the trading goal" },
      { id: "p15", title: "P15", subtitle: "Limiting Beliefs",            slug: "patterns/limiting-beliefs", free: false, starred: false, oneliner: "A limiting belief isn't a personality flaw — it's a conclusion reached from incomplete data" },
    ],
  },
  {
    id: "reference",
    title: "REFERENCE",
    subtitle: "Glossary · FAQ · Depth Dives",
    slug: "reference",
    free: false,
    children: [
      {
        id: "glossary",
        title: "Glossary",
        subtitle: "42 terms defined",
        slug: "reference/glossary",
        free: false,
        starred: false,
        oneliner: "Every term used in the book — precise definitions with cross-references",
      },
      {
        id: "faq",
        title: "FAQ",
        subtitle: "40 questions answered",
        slug: "reference/faq",
        free: false,
        starred: false,
        oneliner: "From 'what is wrong with me?' to 'what do I do tomorrow?' — every common question addressed",
      },
      {
        id: "depth-1",
        title: "Depth Dive 1",
        subtitle: "Systems 1 and 2",
        slug: "reference/depth/1",
        free: false,
        starred: false,
        oneliner: "Kahneman's dual-process theory — why System 1 always wins at the stop level",
      },
      {
        id: "depth-2",
        title: "Depth Dive 2",
        subtitle: "Hyperbolic Discounting",
        slug: "reference/depth/2",
        free: false,
        starred: false,
        oneliner: "Why certainty now beats probability later — every time",
      },
      {
        id: "depth-3",
        title: "Depth Dive 3",
        subtitle: "The Science of Probabilities",
        slug: "reference/depth/3",
        free: false,
        starred: false,
        oneliner: "What a 65% win rate actually means — and what it doesn't",
      },
      {
        id: "depth-4",
        title: "Depth Dive 4",
        subtitle: "Evolutionary Game Theory",
        slug: "reference/depth/4",
        free: false,
        starred: false,
        oneliner: "Why the most sustainable strategy beats the locally optimal one",
      },
      {
        id: "depth-5",
        title: "Depth Dive 5",
        subtitle: "The Hypothetico-Deductive Method",
        slug: "reference/depth/5",
        free: false,
        starred: false,
        oneliner: "Why the variant experiment is the scientific method",
      },
      {
        id: "depth-6",
        title: "Depth Dive 6",
        subtitle: "The Ulysses Contract",
        slug: "reference/depth/6",
        free: false,
        starred: false,
        oneliner: "Why binding future decisions works mechanically, not motivationally",
      },
    ],
  },
];

// Flat list of all sections — useful for prev/next navigation and search
export const ALL_SECTIONS = BOOK_MAP.flatMap((chapter) => [
  { ...chapter, isParent: true },
  ...chapter.children,
]);

// Get a section by slug
export function getSectionBySlug(slug) {
  return ALL_SECTIONS.find((s) => s.slug === slug);
}

// Get prev/next sections (children only, in reading order)
export const READING_ORDER = BOOK_MAP.flatMap((chapter) => chapter.children);

export function getAdjacentSections(slug) {
  const idx = READING_ORDER.findIndex((s) => s.slug === slug);
  return {
    prev: idx > 0 ? READING_ORDER[idx - 1] : null,
    next: idx < READING_ORDER.length - 1 ? READING_ORDER[idx + 1] : null,
  };
}

// Get the parent chapter for a given slug
export function getParentChapter(slug) {
  return BOOK_MAP.find((chapter) =>
    chapter.children.some((child) => child.slug === slug)
  );
}

// Pain-to-pattern quick links (for the "find my pattern" flow)
export const PAIN_LINKS = [
  { pain: "I enter before my level — FOMO, early entries",         slug: "patterns/fomo" },
  { pain: "I hesitate and miss the entry — watch it work without me", slug: "patterns/hesitation" },
  { pain: "I exit trades too early — cut winners before target",    slug: "patterns/early-exit" },
  { pain: "I trade after a loss to win it back",                    slug: "patterns/revenge" },
  { pain: "I move my stop — the loss ends up bigger",               slug: "patterns/stop-tampering" },
  { pain: "I take too many trades — off-plan, can't stop",          slug: "patterns/overtrading" },
  { pain: "I miss the target and give it back — hold too long",     slug: "patterns/greed" },
  { pain: "Bad session — I try to get back to flat, it gets worse", slug: "patterns/redemption" },
  { pain: "After wins I size up and give the gains back",           slug: "patterns/overconfidence" },
  { pain: "I can't take the loss — I know I should",                slug: "patterns/loss-aversion" },
  { pain: "I find reasons to take trades I've already decided on",  slug: "patterns/confirmation" },
  { pain: "Everything looks obvious in hindsight",                  slug: "patterns/hindsight" },
  { pain: "Streaks change my sizing — it costs me",                 slug: "patterns/anchoring" },
  { pain: "I follow the crowd even when it's not my setup",         slug: "patterns/herd" },
  { pain: "I've told myself I'm not good at [X] and I avoid it",   slug: "patterns/limiting-beliefs" },
];
